// <auto-generated />
using System;
using EventCalendarServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventCalendarServer.Migrations
{
    [DbContext(typeof(CalendarEventData))]
    [Migration("20211111060242_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("EventCalendarServer.Models.Events", b =>
                {
                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CommentCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EventsContentsCommentCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Created");

                    b.HasIndex("EventsContentsCommentCreated");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventCalendarServer.Models.EventsContents", b =>
                {
                    b.Property<DateTime?>("CommentCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentCreated");

                    b.ToTable("EventsContents");
                });

            modelBuilder.Entity("EventCalendarServer.Models.Events", b =>
                {
                    b.HasOne("EventCalendarServer.Models.EventsContents", "EventsContents")
                        .WithMany()
                        .HasForeignKey("EventsContentsCommentCreated");

                    b.Navigation("EventsContents");
                });
#pragma warning restore 612, 618
        }
    }
}
